
axon:
  serializer:
    general: jackson
    messages: jackson
    events: jackson
  kafka:
    bootstrap-servers: borker1:9092,broker2:9093
    defaulttopic: domain-events-topic
    producer:
      client-id: 'order-command-service'
      transaction-id-prefix: txPrefix
      retries: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      acks: all
      bootstrap-servers: broker1:9092,broker2:9093

spring:
  data:
    mongodb:
      uri: mongodb://axon:axon@mongodb:27017/axonframework
  output:
    ansi:
      enabled: always

server:
  port: 8081
  servlet:
    context-path: /


logging:
  level:
    org:
      springframework:
        data: DEBUG
    ROOT: DEBUG
    org.axon: DEBUG
    org.apache.kafka: DEBUG