spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/ORDERS_DATABASE
    username: axon
    password: axon
    driver-class-name: 'org.mariadb.jdbc.Driver'
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  output:
    ansi:
      enabled: always


server:
  port: 8080
  servlet:
    context-path: /